=== EVERSE-ResearchSoftware/indicators/tests/dimension_validation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Software Quality Dimension",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "const": "https://w3id.org/everse/rsqd#"
        },
        "@id": {
            "type": "string",
            "format": "uri"
        },
        "@type": {
            "type": "string",
            "const": "SoftwareQualityDimension"
        },
        "name": {
            "type": "string",
            "description": "The name of the quality dimension."
        },
        "description": {
            "type": "string",
            "description": "A detailed description of the quality dimension."
        },
        "identifier": {
            "type": "string",
            "format": "uri",
            "description": "A unique identifier for the quality dimension."
        },
        "keywords": {
            "type": "array",
            "items": { "type": "string" },
            "description": "Keywords describing the quality dimension."
        },
        "author": {
            "type": "string",
            "format": "uri",
            "description": "The author or creator of the quality dimension."
        },
        "created": {
            "type": "string",
            "format": "date-time",
            "description": "The date this quality dimension was created."
        },
        "version": {
            "type": "string",
            "description": "Version number of the quality dimension definition."
        },
        "contact": {
            "type": "string",
            "format": "uri",
            "description": "Contact point for further inquiries."
        },
        "source": {
            "type": "object",
            "description": "Source of the quality dimension definition.",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the source."

                },
                "url": {
                    "type": "string",
                    "description": "URL of the source."
                }
            },
            "required": [
                "name",
                "url"
            ]
        },
        "isPartOf": {
            "type": "object",
            "description": "Indicates a dimension this dimension is part of.",
            "properties": {
                "@id": {
                    "type": "string",
                    "format": "uri"
                }
            }
        }
    },
    "required": [
        "@context",
        "name",
        "description",
        "identifier",
        "source"
    ],
    "additionalProperties": false
}

=== EVERSE-ResearchSoftware/indicators/dimensions/maintainability.json
{
    "@context": "https://w3id.org/everse/rsqd#",
    "@id": "https://w3id.org/everse/i/dimensions/maintainability",
    "@type": "SoftwareQualityDimension",
    "name": "Maintainability",
    "identifier":"https://w3id.org/everse/i/dimensions/maintainability",
    "description": "This characteristic represents the degree of effectiveness and efficiency with which a product or system can be modified to improve it, correct it or adapt it to changes in environment, and in requirements.",
    "source": {
      "name": "ISO/IEC 25010 standard",
      "url": "https://iso25000.com/index.php/en/iso-25000-standards/iso-25010"
      }
  }

=== EVERSE-ResearchSoftware/indicators/dimensions/interaction_capability.json
{
    "@context": "https://w3id.org/everse/rsqd#",
    "@id": "https://w3id.org/everse/i/dimensions/interaction_capability",
    "@type": "SoftwareQualityDimension",
    "name": "Interaction Capability",
    "identifier":"https://w3id.org/everse/i/dimensions/interaction_capability",
    "description": "Degree to which a product or system can be interacted with by specified users to exchange information via the user interface to complete specific tasks in a variety of contexts of use. This characteristic is composed of the following sub-characteristics:\n    - Appropriateness recognizability - Degree to which users can recognize whether a product or system is appropriate for their needs.\n    - Learnability - Degree to which the functions of a product or system can be learnt to be used by specified users within a specified amount of time.\n    - Operability - Degree to which a product or system has attributes that make it easy to operate and control.\n    - User error protection. Degree to which a system prevents users against operation errors.\n    - User engagement - Degree to which a user interface presents functions and information in an inviting and motivating manner encouraging continued interaction.\n    - Inclusivity - Degree to which a product or system can be used by people of various backgrounds (such as people of various ages, abilities, cultures, ethnicities, languages, genders, economic situations, etc.).\n    - User assistance - Degree to which a product can be used by people with the widest range of characteristics and capabilities to achieve specified goals in a specified context of use.\n    - Self-descriptiveness - Degree to wich a product presents appropriate information, where needed by the user, to make its capabilities and use immediately obvious to the user without excessive interactions with a product or other resources (such as user documentation, help desks or other users).",
    "source": {
      "name": "ISO/IEC 25010 standard",
      "url": "https://iso25000.com/index.php/en/iso-25000-standards/iso-25010"
      }
  }

=== EVERSE-ResearchSoftware/indicators/dimensions/functional_suitability.json
{
  "@context": "https://w3id.org/everse/rsqd#",
  "@id": "https://w3id.org/everse/i/dimensions/functional_suitability",
  "@type": "SoftwareQualityDimension",
  "name": "Functional suitability",
  "identifier":"https://w3id.org/everse/i/dimensions/functional_suitability",
  "description": " Represents the degree to which a product or system provides functions that meet stated and implied needs when used under specified conditions",
  "source": {
    "name": "ISO/IEC 25010 standard", 
    "url": "https://iso25000.com/index.php/en/iso-25000-standards/iso-25010"
    }   
}

=== EVERSE-ResearchSoftware/indicators/dimensions/flexibility.json
{
    "@context": "https://w3id.org/everse/rsqd#",
    "@id": "https://w3id.org/everse/i/dimensions/flexibility",
    "@type": "SoftwareQualityDimension",
    "name": "Flexibility",
    "identifier":"https://w3id.org/everse/i/dimensions/flexibility",
    "description": "Degree to which a product can be adapted to changes in its requirements, contexts of use or system environment. This characteristic is composed of the following sub-characteristics:\n    - Adaptability - Degree to which a product or system can effectively and efficiently be adapted for or transferred to different hardware, software or other operational or usage environments.\n    - Scalability - Degree to which a product can handle growing or shrinking workloads or to adapt its capacity to handle variability.\n    - Installability - Degree of effectiveness and efficiency with which a product or system can be successfully installed and/or uninstalled in a specified environment.\n    - Replaceability - Degree to which a product can replace another specified software product for the same purpose in the same environment.",
    "source": {
      "name": "ISO/IEC 25010 standard",
      "url": "https://iso25000.com/index.php/en/iso-25000-standards/iso-25010"
      }
  }

=== EVERSE-ResearchSoftware/indicators/dimensions/performance_efficiency.json
{
    "@context": "https://w3id.org/everse/rsqd#",
    "@id": "https://w3id.org/everse/i/dimensions/performance_efficiency",
    "@type": "SoftwareQualityDimension",
    "name": "Performance Efficiency",
    "identifier":"https://w3id.org/everse/i/dimensions/performance_efficiency",
    "description": "This characteristic represents the degree to which a product performs its functions within specified time and throughput parameters and is efficient in the use of resources (such as CPU, memory, storage, network devices, energy, materials...) under specified conditions.",
    "source": {
      "name": "ISO/IEC 25010 standard",
      "url": "https://iso25000.com/index.php/en/iso-25000-standards/iso-25010"
      }
  }

=== EVERSE-ResearchSoftware/indicators/dimensions/reliability.json
{
    "@context": "https://w3id.org/everse/rsqd#",
    "@id": "https://w3id.org/everse/i/dimensions/reliability",
    "@type": "SoftwareQualityDimension",
    "name": "Reliability",
    "identifier":"https://w3id.org/everse/i/dimensions/reliability",
    "description": "Degree to which a system, product or component performs specified functions under specified conditions for a specified period of time.",
    "source": {
      "name": "ISO/IEC 25010 standard",
      "url": "https://iso25000.com/index.php/en/iso-25000-standards/iso-25010"
      }
  }

=== EVERSE-ResearchSoftware/indicators/dimensions/compatibility.json
{
    "@context": "https://w3id.org/everse/rsqd#",
    "@id": "https://w3id.org/everse/i/dimensions/compatibility",
    "@type": "SoftwareQualityDimension",
    "name": "Compatibility",
    "identifier":"https://w3id.org/everse/i/dimensions/compatibility",
    "description": "Degree to which a product, system or component can exchange information with other products, systems or components, and/or perform its required functions while sharing the same common environment and resources.",
    "source": {
      "name": "ISO/IEC 25010 standard",
      "url": "https://iso25000.com/index.php/en/iso-25000-standards/iso-25010"
      }
  }
