=== EVERSE-ResearchSoftware/indicators/tests/indicator_validation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Software Quality Indicator",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "const": "https://w3id.org/everse/rsqi#"
        },
        "@id": {
            "type": "string",
            "format": "uri"
        },
        "@type": {
            "type": "string",
            "description": "The type of the quality indicator."
        },
        "name": {
            "type": "string",
            "description": "The name of the quality indicator."
        },
        "abbreviation": {
            "type": "string",
            "description": "Abbreviation or short form of the indicator name."
        },
        "alternateName": {
            "type": "string",
            "description": "Alternate name available for the indicator."
        },
        "description": {
            "type": "string",
            "description": "A brief description of the quality indicator."
        },
        "author": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The author of the quality indicator.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"

                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple authors of the quality indicator.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"

                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            }
                        }
                    }
                }
            ]
        },
        "created": {
            "type": "string",
            "format": "date-time",
            "description": "The creation date of the quality indicator."
        },
        "version": {
            "type": "string",
            "description": "The version of the quality indicator."
        },
        "status": {
            "type": "string",
            "description": "The status of the quality indicator."
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Keywords associated with the quality indicator."
        },
        "identifier": {
            "type": "object",
            "description": "An identifier for the quality indicator.",
            "properties": {
                "@id": {
                    "type": "string",
                    "format": "uri"

                }
            }
        },
        "qualityDimension": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The quality dimension this indicator pertains to.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple quality dimensions this indicator pertains to.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            }
                        }
                    }
                }
            ]
        },
        "source": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The source from which this indicator is derived.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        },
                        "identifier": {
                            "type": "string",
                            "format": "uri"
                        },
                        "@type": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name"
                    ]
                },
                {
                    "type": "array",
                    "description": "Multiple sources from which this indicator is derived.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            },
                            "identifier": {
                                "type": "string",
                                "format": "uri"
                            },
                            "@type": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name"
                        ]
                    }
                }
            ]
        },
        "contact": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "contactPoint": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "sameAs": {
            "type": "string",
            "format": "uri",
            "description": "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website."
        }
    },
    "required": [
        "@context",
        "@type",
        "name",
        "abbreviation",
        "description",
        "contact",
        "version",
        "identifier",
        "qualityDimension"
    ],
    "additionalProperties": false
}

=== EVERSE-ResearchSoftware/indicators/indicators/has_contribution_guidelines.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/has_contribution_guidelines",
    "@type": "SoftwareQualityIndicator",
    "name": "Software repository has contribution guidelines",
    "abbreviation": "has_contribution_guidelines",
    "description": "The software repository provides contribution guidelines in case someone wants to contribute to the project.",
    "keywords": [ "linting", "code analysis", "fair"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/has_contribution_guidelines" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "CESSDA"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": [
        {
            "url": "https://docs.tech.cessda.eu/software/requirements.html",
            "name": "Software Requirements"
        }
    ],        
    "qualityDimension": [
        { "@id": "https://w3id.org/everse/i/dimensions/sustaintability" },
        { "@id": "https://w3id.org/everse/i/dimensions/community"},
        { "@id": "https://w3id.org/everse/i/dimensions/open_source_software" }
    ],
    "created": "17-03-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/code_smells_ok.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/code_smells_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Code smells follow community conventions",
  "abbreviation": "code_smells_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/code_smells_ok" },
  "description": "The code smell ratio is maintained at a reasonable level according to community standards and conventions. Code smells are indicators of possible design problems mainly for maintainability of the code (i.e. functions too large, code that is how to read, too many input parameters for a function, etc.). The density of code smells can be estimated with the code smell ratio, an estimator of code smells within a codebase of project often meassured using rule-based checks (i.e. Sonarqube). An example for calculating it could be (code_smells/lines_of_code)*1000.",
  "status": "Active",
  "keywords": [
    "maintainability", "quality", "code smell", "code"
  ],
  "version": "1.0.0",
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
  ],
  "source": [
    {
    "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
    "name": "Socially-Informed Jupyter Notebook Quality: A Role- and Lifecycle-Aware Metrics Framework"
   },
    {
      "name": "A Systematic Literature Review on the Code Smells Datasets and Validation Mechanisms",
      "url":"https://doi.org/10.1145/3596908"
    }
  ],
  "qualityDimension": [
    { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
    { "@id": "https://w3id.org/everse/i/dimensions/community"}
  ],
  "created": "14-04-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/software_has_license_for_file_types.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/software_has_license_for_file_types",
    "@type": "SoftwareQualityIndicator",
    "name": "Software uses an appropriate license for different file types",
    "abbreviation": "software_has_license_for_file_types",
    "description": "This indicator determines if the project has an appropriate licenses for its different file types (e.g., documentation, images, code, tests, etc.). The REUSE specification defines good practices for accomplishing this task.",
    "alternateName": "FRSM-15",
    "keywords": [ "license", "metadata", "fair", "reuse", "reusability" ],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/software_has_license_for_file_types" },
    "status": "Active",
    "version": "1.0.0",
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": [
        {
            "url": "https://github.com/EVERSE-ResearchSoftware/schemas/issues/5",
            "name": "Reusability Conditions"
        },
        {
            "url": "https://fair-impact.github.io/RSMD-guidelines/6.Reuse_legal/",
            "name": "Reuse, licensing and legal aspects. RSMD-6.2"
        }
    ],
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/fairness" },
    "created": "19-05-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/code_churn_ok.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/code_churn_ok",
    "@type": "SoftwareQualityIndicator",
    "name": "Code churn follows community conventions",
    "abbreviation": "code_churn_ok",
    "description": "The code churn (how much a source code has changed over time) of the project's source code is maintained within a reasonable level according to the community's standards and conventions. An example of how to calculate it would be code churn = added lines + deleted lines.",
    "source": {
        "url": "https://ieeexplore.ieee.org/document/738486",
        "name": "Code churn: a measure for estimating the impact of code change"
    },
    "keywords": ["code", "churn", "maintainability"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/code_churn_ok"},
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "status": "Active",
    "version": "1.0.0",
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability"},
    "created": "20-05-2026"
  }

=== EVERSE-ResearchSoftware/indicators/indicators/software_test_coverage.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/software_test_coverage",
  "@type": "SoftwareQualityIndicator",
  "name": "Software has sufficient test coverage",
  "abbreviation": "software_test_coverage",
  "description": "Indicates that the test suite covers most (or ideally all) the code branches, input fields, and functionality",
  "keywords": [
    "test coverage",
    "code coverage",
    "branch coverage",
    "coverage threshold",
    "test completeness"
  ],
  "identifier": {
    "@id": "https://w3id.org/everse/i/indicators/software_test_coverage"
  },
  "status": "Active",
  "version": "0.0.1",
  "author": {
    "@type": "schema:Organization",
    "name": "ELIXIR-Steers",
    "url": "https://elixir-europe.org/about-us/how-funded/eu-projects/steers"
  },
  "contact": [
    {
      "@type": "schema:Person",
      "name": "Daniel Garijo"
    },
    {
      "@type": "schema:Person",
      "name": "Andres Montero"
    }
  ],
  "source": {
    "url": "https://doi.org/10.5281/zenodo.17035105",
    "name": "ELIXIR Steers D2.1 Report on best-practices and indicators available and used by selected Communities"
  },
  "qualityDimension": [
    {
      "@id": "https://w3id.org/everse/i/dimensions/reliability"
    },
    {
      "@id": "https://w3id.org/everse/i/dimensions/functional_suitability"
    }
  ],
  "created": "03-12-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/project_is_active.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/project_is_active",
    "@type": "SoftwareQualityIndicator",
    "name": "Project repository is active",
    "abbreviation": "project_is_active",
    "description": "This indicator aims to determine if a project's repository is maintained by its corresponding maintainers (i.e. commiting within a reasonable time window or having a status of \"Active\").",
    "keywords": [ "active", "project", "repository", "maintainability"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/project_is_active" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": {
        "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#maintained",
        "name": "OpenSSF Scorecard: Maintained"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
    "created": "16-04-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/has_license.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/software_has_license",
    "@type": "SoftwareQualityIndicator",
    "name": "Software has license",
    "abbreviation": "software_has_license",
    "description": "This check tries to determine if the project has published a license",
    "alternateName": "FRSM-15",
    "keywords": [ "license", "metadata", "fair" ],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/software_has_license" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": [
        {
            "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#license",
            "name": "OpenSSF Scorecard: License"
        },
        {
            "url": "https://fair-impact.github.io/RSMD-guidelines/6.Reuse_legal/",
            "name": "Reuse, licensing and legal aspects. RSMD-6.2"
        }
    ],
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/fairness" },
    "created": "23-05-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/repository_workflows.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/repository_workflows",
    "@type": "SoftwareQualityIndicator",
    "name": "Software has ci/cd workflows in its repository",
    "abbreviation": "repository_workflows",
    "description": "This indicator tries aims determine if a software project makes use of workflows to automatize processes like testing and deployment.",
    "keywords": [ "workflows", "github", "fair", "repository"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/repository_workflows" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": [
        {
            "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#ci-tests",
            "name": "OpenSSF Scorecard: CI-Tests"
        }
    ],
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability"},
    "created": "23-05-2025"
}
