=== EVERSE-ResearchSoftware/indicators/tests/indicator_validation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Software Quality Indicator",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "const": "https://w3id.org/everse/rsqi#"
        },
        "@id": {
            "type": "string",
            "format": "uri"
        },
        "@type": {
            "type": "string",
            "description": "The type of the quality indicator."
        },
        "name": {
            "type": "string",
            "description": "The name of the quality indicator."
        },
        "abbreviation": {
            "type": "string",
            "description": "Abbreviation or short form of the indicator name."
        },
        "alternateName": {
            "type": "string",
            "description": "Alternate name available for the indicator."
        },
        "description": {
            "type": "string",
            "description": "A brief description of the quality indicator."
        },
        "author": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The author of the quality indicator.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"

                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple authors of the quality indicator.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"

                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            }
                        }
                    }
                }
            ]
        },
        "created": {
            "type": "string",
            "format": "date-time",
            "description": "The creation date of the quality indicator."
        },
        "version": {
            "type": "string",
            "description": "The version of the quality indicator."
        },
        "status": {
            "type": "string",
            "description": "The status of the quality indicator."
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Keywords associated with the quality indicator."
        },
        "identifier": {
            "type": "object",
            "description": "An identifier for the quality indicator.",
            "properties": {
                "@id": {
                    "type": "string",
                    "format": "uri"

                }
            }
        },
        "qualityDimension": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The quality dimension this indicator pertains to.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple quality dimensions this indicator pertains to.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            }
                        }
                    }
                }
            ]
        },
        "source": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The source from which this indicator is derived.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        },
                        "identifier": {
                            "type": "string",
                            "format": "uri"
                        },
                        "@type": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name"
                    ]
                },
                {
                    "type": "array",
                    "description": "Multiple sources from which this indicator is derived.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            },
                            "identifier": {
                                "type": "string",
                                "format": "uri"
                            },
                            "@type": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name"
                        ]
                    }
                }
            ]
        },
        "contact": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "contactPoint": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "sameAs": {
            "type": "string",
            "format": "uri",
            "description": "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website."
        }
    },
    "required": [
        "@context",
        "@type",
        "name",
        "abbreviation",
        "description",
        "contact",
        "version",
        "identifier",
        "qualityDimension"
    ],
    "additionalProperties": false
}

=== EVERSE-ResearchSoftware/indicators/indicators/uses_fuzzing.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/fuzzing_use",
    "@type": "SoftwareQualityIndicator",
    "name": "Software uses fuzzing",
    "abbreviation": "fuzzing_use",
    "description": "This indicator checks that If the software produced by the project includes software written using a memory-unsafe language (e.g., C or C++), then at least one dynamic tool (e.g., a fuzzer or web application scanner) be routinely used in combination with a mechanism to detect memory safety problems such as buffer overwrites. ",
    "keywords": [ "fuzzing", "test", "code"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/fuzzing_use" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": {
        "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#fuzzing",
        "name": "OpenSSF Scorecard: Fuzzing"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/safety" },
    "created": "23-06-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/functional_correctness.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/functional_correctness",
  "@type": "SoftwareQualityIndicator",
  "name": "Has a measure of functional correctness",
  "abbreviation": "functional_correctness",
  "description": "For analysis code specifically, is there a quantifiable measure of the functional correctness of the software output. This indicator focuses on computational/statistical correctness. For example, in an ML model software context, the indicator measures whether the repository reports metrics like Accuracy, F1-score, or ROC-AUC to prove the model performs as intended. However other performance metrics may also address the indicator. Evaluation metrics may be provided through documentation, tables or scripts available in the source code of the target tool.",
  "source": {
    "@id": "https://dome-ml.org/guidelines",
    "url": "https://dome-ml.org/guidelines#evaluation-section",
    "name": "DOME Recommendations for Supervised Machine Learning (Evaluation section)"
  },
  "keywords": [
    "correctness",
    "machine learning",
    "models"
  ],
  "identifier": {
    "@id": "https://w3id.org/everse/i/indicators/functional_correctness"
  },
  "status": "Active",
  "version": "1.0.0",
  "author": {
    "@type": "schema:Organization",
    "name": "University of Padova"
  },
  "contact": {
    "@type": "schema:Person",
    "name": "Gavin Farrell",
    "email": "gavinmichael.farrell@studenti.unipd.it"
  },
  "qualityDimension": {
    "@id": "https://w3id.org/everse/i/dimensions/functional_suitability"
  },
  "created": "03-12-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/code_documentation_coverage_ok.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/code_documentation_coverage_ok",
    "@type": "SoftwareQualityIndicator",
    "name": "The documentation coverage for the codebase follows community conventions",
    "abbreviation": "code_documentation_coverage_ok",
    "description": "This check tries to determine if the project's codebase is mostly documented according according to community conventions and standards (i.e. docstrings).",
    "source": {
        "url": "https://interrogate.readthedocs.io/en/latest/",
        "name": "interrogate"
    },
    "keywords": ["documentation", "docstring", "documentation coverage"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/code_documentation_coverage_ok"},
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "status": "Active",
    "version": "1.0.0",
    "qualityDimension": [
        { "@id": "https://w3id.org/everse/i/dimensions/maintainability"},
        { "@id": "https://w3id.org/everse/i/dimensions/fairness"}
    ],
    "created": "20-05-2026"
  }

=== EVERSE-ResearchSoftware/indicators/indicators/internal_cohesion.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/internal_cohesion",
  "@type": "SoftwareQualityIndicator",
  "name": "Cohesion among methods/functions of a module follows community conventions",
  "abbreviation": "internal_cohesion",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/internal_cohesion" },
  "description": "The cohesion among methods/functions of a module is maintained to a reasonable level according to community expectations and standards. Cohesion describes how related the functions within a single module are. Low cohesion implies that a given module performs tasks which are not very related to each other and hence can create problems as the module becomes large",
  "status": "Active",
  "keywords": [
    "maintainability", "cohesion", "module", "code"
  ],
  "version": "1.0.0",
  "author": {
    "@type": "schema:Person",
    "name": "Daniel Garijo"
  },
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": [
    {
      "identifier": "https://zenodo.org/records/10647227",
      "url": "https://zenodo.org/records/10647227",
      "name": "Internal cohesion"
    },
    {
      "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
      "name": "Cohesion among methods"
    }
  ],
  "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
  "created": "11-03-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/maintainability_index_ok.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/maintainability_index_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Maintainability index follows community conventions",
  "abbreviation": "maintainability_index_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/maintainability_index_ok" },
  "description": "The maintainability index (i.e., degree of effectiveness and efficiency with which a product or system can be modified by the intended maintainers) should follow conventions and standards established by the community responsible for maintaining the source code or system. The maintainability index depends on 3 main factors: cyclomatic complexiy, lines of code and halstead volume (amount of information that needs to be processed to understand the code). An example for calculating it could be MAX(0,(171 - 5.2 * ln(Halstead Volume) - 0.23 * (Cyclomatic Complexity) - 16.2 * ln(Lines of Code))*100 / 171).",
  "status": "Active",
  "keywords": [
    "maintainability", "code", "maintainability index"
  ],
  "version": "1.0.0",
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": [
    {
      "identifier": "https://zenodo.org/records/10647227",
      "url": "https://zenodo.org/records/10647227",
      "name": "Task Force Sub Group 3 - Review of Software Quality Attributes and Characteristics"
    },
    {
      "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
      "name": "Socially-Informed Jupyter Notebook Quality: A Role- and Lifecycle-Aware Metrics Framework"
    },
    {
      "url": "https://learn.microsoft.com/en-us/visualstudio/code-quality/code-metrics-maintainability-index-range-and-meaning?view=visualstudio",
      "name": "Code metrics - Maintainability index range and meaning"
    }
  ],
  "qualityDimension": [
    { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
    { "@id": "https://w3id.org/everse/i/dimensions/community"}
  ],
  "created": "14-04-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/listed_in_registry.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/listed_in_registry",
    "@type": "SoftwareQualityIndicator",
    "name": "Software is listed in a registry",
    "abbreviation": "listed in registry",
    "description": "The target source code repository is in a disciplinary or community registry (e.g ascl.net, bio.tools, swMath, RRID portal, RSD, WikiData, DataCite, etc.) to ensure that software can be found and accessed.",
    "source": {
        "@id": "https://fair-impact.github.io/RSMD-guidelines/8.rsmd_checklist/",
        "url": "https://fair-impact.github.io/RSMD-guidelines/8.rsmd_checklist/#accessibility-and-preservation",
        "name": "Accesibility and preservation. RSMD 2.3"
    },
    "keywords": ["repository", "fair", "software heritage, zenodo"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/listed_in_registry"},
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "FAIR-IMPACT"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/fairness" },
    "created": "23-06-2025"
  }

=== EVERSE-ResearchSoftware/indicators/indicators/response_timeframe_ok.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/response_timeframe_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Responses to issues and/or pull requests are done within a defined timeframe",
  "abbreviation": "response_timeframe_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/response_timeframe_ok" },
  "description": "The maintainers of the project's repository respond to issues and/or pull requests within a defined time frame that follows the related community's conventions.",
  "status": "Active",
  "keywords": [
    "response", "issue", "pull request", "timeframe"
  ],
  "version": "1.0.0",
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": {
        "name": "2.5 Community",
        "url": "https://github.com/EVERSE-ResearchSoftware/reference-framework/blob/main/source/02-framework/community.md"
  },
  "qualityDimension": [
        { "@id": "https://w3id.org/everse/i/dimensions/community"},
        { "@id": "https://w3id.org/everse/i/dimensions/open_source_software" }
  ],
  "created": "18-05-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/coupling_between_objects_ok.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/coupling_between_objects_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Coupling between objects follows community conventions",
  "abbreviation": "coupling_between_objects_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/coupling_between_objects_ok" },
  "description": "The coupling between objects (CBO) ratio is maintained at a reasonable level according to the community's standards or expectations",
  "status": "Active",
  "keywords": [
    "maintainability", "coupling, software"
  ],
  "version": "1.0.0",
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": [
    {
      "identifier": "https://zenodo.org/records/10647227",
      "url": "https://zenodo.org/records/10647227",
      "name": "Task Force Sub Group 3 - Review of Software Quality Attributes and Characteristics"
    },
    {
      "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
      "name": "Socially-Informed Jupyter Notebook Quality: A Role- and Lifecycle-Aware Metrics Framework"
    }
  ],
  "qualityDimension": [
    { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
    { "@id": "https://w3id.org/everse/i/dimensions/community"}
  ],
  "created": "11-03-2026"
}
