=== EVERSE-ResearchSoftware/indicators/tests/indicator_validation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Software Quality Indicator",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "const": "https://w3id.org/everse/rsqi#"
        },
        "@id": {
            "type": "string",
            "format": "uri"
        },
        "@type": {
            "type": "string",
            "description": "The type of the quality indicator."
        },
        "name": {
            "type": "string",
            "description": "The name of the quality indicator."
        },
        "abbreviation": {
            "type": "string",
            "description": "Abbreviation or short form of the indicator name."
        },
        "alternateName": {
            "type": "string",
            "description": "Alternate name available for the indicator."
        },
        "description": {
            "type": "string",
            "description": "A brief description of the quality indicator."
        },
        "author": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The author of the quality indicator.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"

                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple authors of the quality indicator.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"

                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            }
                        }
                    }
                }
            ]
        },
        "created": {
            "type": "string",
            "format": "date-time",
            "description": "The creation date of the quality indicator."
        },
        "version": {
            "type": "string",
            "description": "The version of the quality indicator."
        },
        "status": {
            "type": "string",
            "description": "The status of the quality indicator."
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Keywords associated with the quality indicator."
        },
        "identifier": {
            "type": "object",
            "description": "An identifier for the quality indicator.",
            "properties": {
                "@id": {
                    "type": "string",
                    "format": "uri"

                }
            }
        },
        "qualityDimension": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The quality dimension this indicator pertains to.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple quality dimensions this indicator pertains to.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            }
                        }
                    }
                }
            ]
        },
        "source": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "The source from which this indicator is derived.",
                    "properties": {
                        "@id": {
                            "type": "string",
                            "format": "uri"

                        },
                        "identifier": {
                            "type": "string",
                            "format": "uri"
                        },
                        "@type": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name"
                    ]
                },
                {
                    "type": "array",
                    "description": "Multiple sources from which this indicator is derived.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri"

                            },
                            "identifier": {
                                "type": "string",
                                "format": "uri"
                            },
                            "@type": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name"
                        ]
                    }
                }
            ]
        },
        "contact": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "contactPoint": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Contact point for more information.",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "format": "uri"
                        },
                "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string",
                            "format": "email"
                        }
                    }
                },
                {
                    "type": "array",
                    "description": "Multiple contact points for more information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "format": "uri"
                            },
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string",
                                "format": "email"
                            }
                        }
                    }
                }
            ]
        },
        "sameAs": {
            "type": "string",
            "format": "uri",
            "description": "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website."
        }
    },
    "required": [
        "@context",
        "@type",
        "name",
        "abbreviation",
        "description",
        "contact",
        "version",
        "identifier",
        "qualityDimension"
    ],
    "additionalProperties": false
}

=== EVERSE-ResearchSoftware/indicators/indicators/internal_cohesion_ok.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/internal_cohesion_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Cohesion among methods/functions of a module follows community conventions",
  "abbreviation": "internal_cohesion_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/internal_cohesion_ok" },
  "description": "The cohesion among methods/functions of a module is maintained to a reasonable level according to community expectations and standards. Cohesion describes how related the functions within a single module are. Low cohesion implies that a given module performs tasks which are not very related to each other and hence can create problems as the module becomes large",
  "status": "Active",
  "keywords": [
    "maintainability", "cohesion", "module", "code"
  ],
  "version": "1.0.0",
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": [
    {
      "identifier": "https://zenodo.org/records/10647227",
      "url": "https://zenodo.org/records/10647227",
      "name": "Task Force Sub Group 3 - Review of Software Quality Attributes and Characteristics"
    },
    {
      "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
      "name": "Socially-Informed Jupyter Notebook Quality: A Role- and Lifecycle-Aware Metrics Framework"
    }
  ],
  "qualityDimension": [
    { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
    { "@id": "https://w3id.org/everse/i/dimensions/community"}
  ],
  "created": "11-03-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/support_issue_tracking.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/support_issue_tracking",
    "@type": "SoftwareQualityIndicator",
    "name": "Software provides issue tracking",
    "abbreviation": "support_issue_tracking",
    "description": "The software project offers an accessible issue tracking system (e.g., GitHub/GitLab Issues or a helpdesk) that is used to report, document, and manage bugs, enhancement requests, and user-facing operational issues.",
    "source": {
        "@id": "https://zenodo.org/records/17035105",
        "url": "https://zenodo.org/records/17035105",
        "name": "ELIXIR-STEERS D2.1 Report on best-practices and indicators available and used by selected Communities"
    },
    "keywords": ["support", "issues", "helpdesk", "maintenance", "user support"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/support_issue_tracking"},
    "status": "Active",
    "version": "1.0.0",
    "author": {
        "@type": "Organization",
        "name": "OpenSSF",
        "url": "https://openssf.org/"
    },
    "contact": {
        "@type": "schema:Person",
        "name": "Federica Quaglia",
        "email": "federica.quaglia@unipd.it"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability"},
    "created": "03-12-2025"
 }

=== EVERSE-ResearchSoftware/indicators/indicators/archived_in_scholarly_repository.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/archived_in_scholarly_repository",
    "@type": "SoftwareQualityIndicator",
    "name": "Software is archived in a scholarly repository",
    "abbreviation": "archived_in_scholarly_repository",
    "description": "The source code repository is archived in a scholarly repository (e.g Zenodo, HAL) to ensure that software can be found and accessed in a scholarly context.",
    "source": {
        "@id": "https://fair-impact.github.io/RSMD-guidelines/8.rsmd_checklist/",
        "url": "https://fair-impact.github.io/RSMD-guidelines/8.rsmd_checklist/#accessibility-and-preservation",
        "name": "Accessibility and preservation. RSMD 2.2"
    },
    "keywords": ["repository", "fair", "scholar"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/archived_in_scholarly_repository"},
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "FAIR-IMPACT"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/fairness" },
    "created": "23-06-2025"
  }

=== EVERSE-ResearchSoftware/indicators/indicators/human_code_review_requirement.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/human_code_review_requirement",
    "@type": "SoftwareQualityIndicator",
    "name": "Software requires human code review.",
    "abbreviation": "human code review requirement",
    "description": "This indicator aims to determine if a software project requires human code review before pull requests.",
    "keywords": ["human-in-the-loop","pull request","review"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/human_code_review_requirement" },
    "status": "Active",
    "version": "1.0.0",
    "author" : {
        "@type" : "schema:Organization",
        "name" : "OpenSSF",
        "url" : "https://openssf.org/"
    },
    "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
    "source": {
        "url": "https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#code-review",
        "name": "OpenSSF Scorecard: Code-Review"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/functional_suitability" },
    "created": "23-05-2025"
}

=== EVERSE-ResearchSoftware/indicators/indicators/cyclomatic_complexity.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/cyclomatic_complexity_ok",
  "@type": "SoftwareQualityIndicator",
  "name": "Cyclomatic complexity follows community conventions",
  "abbreviation": "cyclomatic_complexity_ok",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/cyclomatic_complexity_ok" },
  "description": "Cyclomatic complexity (i.e., the number of linearly independent paths through a program’s source code) of the whole software component or modules/components/classes/functions/methods should follow the conventions established by the community  responsible for maintaining the tool. Cyclomatic complexity is created by calculating the number of different code paths in the flow of the program. A program that has complex control flow requires more tests to achieve good code coverage and is less maintainable.",
  "status": "Active",
  "keywords": [
    "maintainability", "complexity, code"
  ],
  "version": "1.0.0",
  "author": {
    "@type": "schema:Person",
    "name": "Daniel Garijo"
  },
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": [
    {
      "identifier": "https://zenodo.org/records/10647227",
      "url": "https://zenodo.org/records/10647227",
      "name": "Task Force Sub Group 3 - Review of Software Quality Attributes and Characteristics"
    },
    {
      "url": "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11216562&tag=1",
      "name": "Socially-Informed Jupyter Notebook Quality: A Role- and Lifecycle-Aware Metrics Framework"
    }
  ],
  "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/maintainability" },
  "created": "10-03-2026"
}

=== EVERSE-ResearchSoftware/indicators/indicators/has_no_binary_artifacts.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/has_no_binary_artifacts",
    "@type": "SoftwareQualityIndicator",
    "name": "Project repository has no binary artifacts",
    "abbreviation": "has_no_binary_artifacts",
    "description": "The repository does not contain binary artifacts. Binary artifacts are files generated by compilation or packaging tools that contain code that is no longer human-readable (i.e. .class, .jar, .war, .pyc, etc.).",
    "source": {
        "url": "https://github.com/ossf/scorecard/blob/c22063e786c11f9dd714d777a687ff7c4599b600/docs/checks.md#binary-artifacts",
        "name": "Binary-Artifacts"
    },
    "keywords": ["binary artifact", "repository"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/has_no_binary_artifacts"},
    "status": "Active",
    "version": "1.0.0",
    "author": {
        "@type": "Organization",
        "name": "OpenSSF",
        "url": "https://openssf.org/"
    },
    "contact": [
        {
            "@type": "schema:Person",
            "name": "Daniel Garijo",
            "email": "daniel.garijo@upm.es"
        },
        {
            "@type": "schema:Person",
            "name": "Andres Montero",
            "email": "andres.montero.martin@upm.es"
        }
    ],
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/security"},
    "created": "13-05-2026"
  }

=== EVERSE-ResearchSoftware/indicators/indicators/static_analysis_common_vulnerabilities.json
{
    "@context": "https://w3id.org/everse/rsqi#",
    "@id": "https://w3id.org/everse/i/indicators/static_analysis_common_vulnerabilities",
    "@type": "SoftwareQualityIndicator",
    "name": "Has static analysis for common vulnerabilities",
    "abbreviation": "static_analysis_common_vulnerabilities",
    "description": "At least one static code analysis tool used includes rules or techniques to detect common vulnerabilities specific to the language or environment.",
    "source": {
        "@id": "https://www.bestpractices.dev/en/criteria/0",
        "url": "https://www.bestpractices.dev/en/criteria/0#0.static_analysis_common_vulnerabilities",
        "name": "FLOSS Best Practices Criteria (Passing Badge)"
    },
    "keywords": ["security", "vulnerabilities", "static analysis"],
    "identifier": { "@id": "https://w3id.org/everse/i/indicators/static_analysis_common_vulnerabilities"},
    "status": "Active",
    "version": "1.0.0",
    "author": {
        "@type": "Organization",
        "name": "OpenSSF",
        "url": "https://openssf.org/"
    },
    "contact": {
        "@type": "schema:Person",
        "name": "Thomas Vuillaume",
        "email": "thomas.vuillaume@lapp.in2p3.fr"
    },
    "qualityDimension": { "@id": "https://w3id.org/everse/i/dimensions/security"},
    "created": "03-04-2025"
  }

=== EVERSE-ResearchSoftware/indicators/indicators/has_active_contributors.json
{
  "@context": "https://w3id.org/everse/rsqi#",
  "@id": "https://w3id.org/everse/i/indicators/has_active_contributors",
  "@type": "SoftwareQualityIndicator",
  "name": "Project has active contributors beyond core maintainers",
  "abbreviation": "has_active_contributors",
  "identifier": { "@id": "https://w3id.org/everse/i/indicators/has_active_contributors" },
  "description": "Contributions and/or other additions/updates to the project aren't centralised on only the core maintainers, but also other contributors.",
  "status": "Active",
  "keywords": [
    "contributor", "active"
  ],
  "version": "1.0.0",
  "contact": [
    {
        "@type": "schema:Person",
        "name": "Daniel Garijo"
    },
    {
        "@type": "schema:Person",
        "name": "Andres Montero"
    }
    ],
  "source": {
        "name": "2.5 Community",
        "url": "https://github.com/EVERSE-ResearchSoftware/reference-framework/blob/main/source/02-framework/community.md"
  },
  "qualityDimension": [
        { "@id": "https://w3id.org/everse/i/dimensions/community"},
        { "@id": "https://w3id.org/everse/i/dimensions/open_source_software" }
  ],
  "created": "18-05-2026"
}
